services:
  vpn:
    image: qmcgaw/gluetun
    container_name: qbittorrent-vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USER}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - SERVER_COUNTRIES=${NORDVPN_COUNTRY}
      - FIREWALL=on
      - FIREWALL_VPN_INPUT_PORTS=8081,6881
      - HEALTH_VPN_DURATION_INITIAL=30s
      - HEALTH_VPN_DURATION_ADDITION=5s
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:6881:6881"
      - "127.0.0.1:6881:6881/udp"
    volumes:
      - ./vpn-config:/gluetun
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:vpn"
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8081
    volumes:
      - /mnt/storage/Media/:/downloads
      - ./data/config:/config
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8081",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
