services:
  vpn:
    image: qmcgaw/gluetun
    container_name: bun-vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORDVPN_USER}
      - OPENVPN_PASSWORD=${NORDVPN_PASSWORD}
      - SERVER_COUNTRIES=${NORDVPN_COUNTRY}
      - FIREWALL=on
      - FIREWALL_VPN_INPUT_PORTS=8080
      - HEALTH_VPN_DURATION_INITIAL=30s
      - HEALTH_VPN_DURATION_ADDITION=5s
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped

  bun:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun
    network_mode: "service:vpn"
    depends_on:
      - vpn
    volumes:
      - ./data:/home/bun/data
      - ../../snublecron:/home/bun/snublejuice
    stdin_open: true
    tty: true
    restart: unless-stopped
