services:
  torrenting:
    build: .
    container_name: playground-torrenting
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ./data/downloads:/home/downloads
      - ./data/config:/home/config
      - ./data/vpn:/etc/openvpn/nordvpn
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M
    networks:
      - torrenting-net
    environment:
      - TZ=UTC
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    dns:
      - 1.1.1.1
      - 8.8.8.8
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "--max-time", "10", "http://ifconfig.me"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  torrenting-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16

volumes:
  torrenting-downloads:
    driver: local
  torrenting-config:
    driver: local