services:
  torrenting:
    build:
      context: ..
      dockerfile: torrenting/Dockerfile
    container_name: playground-torrenting
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:6881:6881"
      - "127.0.0.1:6881:6881/udp"
    volumes:
      # Bind mount to local directory
      - E:/:/home/downloads
      - ./data/config:/home/config

      # VPN configuration mount
      - ../vpn/config:/etc/openvpn/nordvpn

      # Temporary filesystem for /tmp
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M
    networks:
      - playground-net
    environment:
      - TZ=UTC
      - PUID=1000
      - PGID=1000
      - SERVICE_TYPE=torrenting
    # Resource limits for safety
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4.0'
    # Security options - modified for VPN requirements
    security_opt:
      - no-new-privileges:true
    # Capabilities needed for VPN
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/health-check.sh"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 2m

networks:
  playground-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

# Define named volumes
volumes:
  playground-data:
    driver: local
  playground-projects:
    driver: local