services:
  cpp:
    build: .
    container_name: playground-cpp
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      # Bind mount to local directory
      - ../../cpp:/home/cpp

      # Temporary filesystem for /tmp
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M
    networks:
      - cpp-net
    # Resource limits for safety
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    # Security options
    security_opt:
      - no-new-privileges:true
    # Remove capabilities
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    # Read-only root filesystem (optional - uncomment if you want extra isolation)
    # read_only: true
    # tmpfs:
    #   - /tmp
    #   - /var/tmp

networks:
  cpp-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

# Define named volumes
volumes:
  playground-data:
    driver: local
  playground-projects:
    driver: local
