services:
  torrenting:
    build: .
    container_name: playground-torrenting-vpn
    privileged: true  # Required for VPN and iptables
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:8080:8080"  # qBittorrent Web UI
    volumes:
      # Downloads directory
      - ./data/downloads:/home/downloads
      
      # qBittorrent configuration
      - ./data/config:/home/config
      
      # NordVPN configuration (you need to add these files)
      - ./data/vpn:/etc/openvpn/nordvpn
      
      # Temporary filesystem for /tmp
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M
    networks:
      - torrenting-net
    environment:
      # Set timezone
      - TZ=UTC
      # qBittorrent settings
      - WEBUI_PORT=8080
    # Resource limits for safety
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    # DNS settings (will be overridden by VPN)
    dns:
      - 1.1.1.1
      - 8.8.8.8
    # Capabilities needed for VPN and container operations
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    # Restart policy
    restart: unless-stopped
    # Health check to ensure VPN is working
    healthcheck:
      test: ["CMD", "curl", "-f", "--max-time", "10", "http://ifconfig.me"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  torrenting-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16

# Define named volumes
volumes:
  torrenting-downloads:
    driver: local
  torrenting-config:
    driver: local