services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - /mnt/storage/Jellyfin/Config:/config
      - /mnt/storage/Jellyfin/Cache:/cache
      - type: bind
        source: /mnt/storage/Media
        target: /media
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: "unless-stopped"
