services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25565:25565/tcp"
    environment:
      EULA: TRUE
      TYPE: PAPER
      VERSION: LATEST
      MOTD: "\u00A7kiii\u00A7r \u00A72\u00A7lS N U B L E J U I C E\u00A7r \u00A7kiii"
      OVERRIDE_ICON: TRUE
      ICON: "https://raw.githubusercontent.com/hallvardnmbu/snublejuice/main/src/public/images/64x64.png"
      WHITELIST: |
        Hallvard
        Halli
        FishbollKing
        chicken_boss10
        Bokaiii
        Cella555
      MAX_MEMORY: 6G
      TZ: "Europe/Oslo"
      DIFFICULTY: normal
      MAX_PLAYERS: 9
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 12
      GUI: FALSE
      SNOOPER_ENABLED: FALSE
    volumes:
      - ../../../Minecraft/snublejuice:/data
    restart: "unless-stopped"
