services:
  snublejuice:
    build: .
    container_name: playground-snublejuice
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      # Bind mount to local directory
      - ./data:/home/data
      - ../../snublejuice:/home/snublejuice